org: dasniko
app: xmas
service: days-until-xmas

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-central-1
  memorySize: 128
  timeout: 3
  stage: demo
  deploymentBucket: dasniko.serverless.deployments.${self:provider.region}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - sns:Publish
      Resource: "${file(sls-props.yml):dlq}"
  environment:
    TWITTER_CONSUMER_KEY: ${file(sls-props.yml):twitter.consumer_key}
    TWITTER_CONSUMER_SECRET: ${file(sls-props.yml):twitter.consumer_secret}
    TWITTER_ACCESS_TOKEN_KEY: ${file(sls-props.yml):twitter.access_token_key}
    TWITTER_ACCESS_TOKEN_SECRET: ${file(sls-props.yml):twitter.access_token_secret}

functions:
  cron:
    handler: index.handler
    events:
      # starting Nov 24, every day at 09:02 (GMT)
      - schedule: cron(2 9 24-30 11 ? *)
      # until Dec 24, every day at 09:02 (GMT)
      - schedule: cron(2 9 1-24 12 ? *)
      # Jan - Oct, on 24th of month at 08:05 (GMT)
      - schedule: cron(5 8 24 1-10 ? *)
    onError: "${file(sls-props.yml):dlq}"
